### ISSUE TITLE
In place of manually calling `mentions-workflow.yml` you can trigger on `Add mention` on issue created.

### ISSUE THREAD

**Issue by oyetanishq** [matyo91/matyo91#7]
[Trigger Event Docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues)

```yml
on:
  issues:
    types: [opened, edited, milestoned]
```

and after this workflow trigger we can add a condition to check if the issue is legit or it's `Add mention` one.

```yml
if: github.event.issue.title == 'Add My Name' || github.event.issue.title == 'add my name'
```
